function Lorem() {
    return (
        <p className="bg-neutral-100 dark:bg-neutral-800 text-neutral-950 dark:text-neutral-200">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta et exercitationem velit vitae sapiente voluptas accusamus expedita architecto nostrum. Delectus laudantium aperiam fugit repellat cumque nam dolorum quo reprehenderit alias?
            Omnis iure dicta est vel quo dolores illo? Et rerum nulla qui beatae harum, eos quod quos eius voluptatem doloremque provident labore repellendus hic aspernatur voluptate. Facilis ab commodi dicta?
            Eum vel repellendus, error quam nemo ut, enim fugiat atque tempora cupiditate harum ratione modi sit. Libero odio inventore nostrum beatae iste iusto, hic aut possimus accusantium nisi repudiandae nobis.
            Recusandae perspiciatis enim ab nesciunt, ipsum hic natus numquam tempore harum officiis atque commodi dolores eius unde eveniet culpa adipisci saepe eaque illo dolorem laborum nemo omnis? Tenetur, debitis enim.
            Deserunt architecto aliquam quidem quae dolorum temporibus vel repellat commodi esse ullam enim, ad accusamus illo voluptatum nostrum molestias ex! Necessitatibus esse quaerat dolorum eveniet fuga cumque, accusamus tempora tenetur?
            Culpa perferendis nobis consequuntur in pariatur, labore, provident eius quas sequi perspiciatis explicabo excepturi exercitationem vel mollitia? Maiores, corrupti pariatur! Mollitia similique quam maxime non illum dolorem soluta nulla sint?
            Voluptatem excepturi quod aliquid atque, non obcaecati aperiam neque dolorem, ullam, a vero officia similique quaerat facere. Ipsa, sed eius deserunt, tempore voluptate odit natus impedit soluta omnis est harum.
            Pariatur ad earum numquam suscipit necessitatibus, id ducimus facere fugiat adipisci eveniet ipsa minima ratione optio aliquam, eaque excepturi assumenda accusantium laborum! Excepturi, inventore architecto. Fugiat recusandae natus molestiae voluptatibus.
            Vel voluptas corrupti asperiores nobis iure in, veniam voluptates quas, nulla eius amet provident optio, ducimus animi ut! Incidunt odio ea fuga facere obcaecati asperiores inventore, voluptatibus perspiciatis cum tempora?
            Maxime sit totam tempore, provident facilis quidem dolorum, velit distinctio ratione a recusandae accusamus et amet unde eligendi nam iste ea reprehenderit, error possimus aliquam? Hic amet animi provident explicabo?
            Ea hic rem assumenda quasi maxime et suscipit porro tempora soluta quae inventore perspiciatis laudantium consequatur distinctio, mollitia odio natus aliquid exercitationem eveniet. Libero explicabo omnis atque dolorem necessitatibus? Sunt.
            Molestias, nostrum accusamus error, assumenda sit corrupti libero in possimus quaerat alias ducimus, suscipit architecto vitae dolores? Repudiandae consequuntur voluptatibus impedit, illo minus repellendus blanditiis autem praesentium, debitis nulla quam.
            Nostrum provident quisquam atque dolores aperiam odit similique rerum fuga repellendus! Delectus maxime, nesciunt temporibus beatae incidunt molestias illum totam animi perferendis dolor ratione voluptatum officia voluptates nihil ea aliquid?
            Quia iusto, omnis qui vero neque odio excepturi eius aliquid quaerat, repellendus blanditiis laborum cupiditate sapiente error minus quibusdam nulla est! Quisquam, totam. Veritatis, sint laudantium vel esse numquam voluptatibus.
            Iusto recusandae doloribus laudantium qui, adipisci earum? Vitae amet quasi sint labore eum, ex atque pariatur eius ducimus quibusdam, adipisci praesentium id ab exercitationem sed tempore culpa error distinctio voluptatem!
            Dicta eum explicabo hic architecto nisi deleniti quaerat. Error accusamus placeat temporibus iusto veritatis eos pariatur dicta ipsam debitis maxime, iure voluptatum ducimus cumque, sequi modi. Minima aut nemo corrupti.
            Cum at sunt ipsam, accusantium labore eum esse. Adipisci saepe odio expedita, magnam sequi dolor! Distinctio pariatur tempore nihil eveniet voluptates quaerat ipsum rem cum cumque. Neque maiores ut quia?
            Voluptatibus cupiditate ducimus expedita inventore ad, eaque et, mollitia doloremque commodi ullam cum itaque nemo blanditiis deserunt! In voluptate exercitationem, at vero perferendis temporibus saepe, earum est, deserunt aut porro!
            Asperiores nostrum quos blanditiis deleniti ipsam dolorum, dicta impedit facere. Nam tenetur modi deserunt odit? Consequuntur exercitationem doloremque delectus soluta, aliquam nam veritatis eveniet voluptas, dolorum voluptates, repellendus in rerum?
            Odio quidem corporis quam blanditiis nobis doloribus commodi, excepturi quasi est dolores harum, iste odit, officia vitae doloremque cupiditate id quae sit similique necessitatibus fuga labore molestias. Atque, qui error?
            Doloribus voluptates eius vitae odit optio officia provident deleniti voluptatibus cumque natus culpa aperiam et eaque, mollitia repellendus doloremque facilis, modi quasi incidunt, molestias minima sequi eligendi! Possimus, excepturi enim.
            Dignissimos quo sint quibusdam temporibus neque, dicta sequi inventore blanditiis, sapiente, id eligendi provident itaque pariatur minima voluptate aliquid debitis. Ratione ex aut vitae totam excepturi fuga rerum, dolor illum.
            Error eligendi est molestias a qui quasi aperiam, ea possimus et nihil perspiciatis culpa exercitationem ipsa harum odio voluptates, provident commodi autem quas quia eum rerum eius blanditiis quam. Consequuntur.
            Alias doloribus voluptate ratione rerum quidem porro ipsum cum soluta harum est ex delectus, illo fugit voluptatum non magni qui earum vero quae debitis, repellendus ea! Deserunt quam rerum voluptates.
            Enim, similique exercitationem. Nesciunt quis saepe a tempore explicabo deleniti eligendi. Reprehenderit maiores quasi doloribus maxime voluptates id esse. Et iure illo quidem dolores maxime velit incidunt! Consectetur, quo repellendus!
            Animi illo similique numquam incidunt repellat in doloribus placeat. Sequi voluptas vero modi esse ad voluptatum ullam fugit aspernatur! Voluptas necessitatibus cumque eveniet mollitia commodi maiores labore adipisci distinctio fugiat.
            Aspernatur molestiae voluptatem voluptate adipisci ipsam repellat accusamus magni esse quo debitis tempora amet velit maxime minima aliquam, sit nam veniam nesciunt. Possimus nobis in inventore repudiandae, sint odio totam!
            Tenetur earum quasi assumenda exercitationem architecto ratione recusandae, reprehenderit maxime blanditiis dignissimos consequatur? Esse vero, aut magni qui quam, fuga incidunt aliquid doloribus earum fugiat dolorum veritatis dicta ex molestiae?
            Dicta dolor eius, provident delectus ab necessitatibus asperiores expedita dignissimos eaque veritatis reprehenderit dolorem illum distinctio? Et non facere illum vel eum quae cumque quos ea repudiandae, porro iusto fugiat.
            Impedit ratione magnam similique unde voluptatum reiciendis culpa odit optio qui, cum officia dolorum modi deserunt sapiente quibusdam, quisquam officiis, quod nulla. Quo fugiat asperiores laborum numquam tempora iste officiis!
            Exercitationem optio eius dolor quidem animi voluptatibus, sequi, provident laboriosam aut ad deleniti a magni voluptas earum autem. Iusto excepturi enim debitis sunt ad velit animi soluta, dignissimos obcaecati esse!
            Alias sed velit ratione voluptatem labore rerum quas quod tempora blanditiis autem nisi quisquam culpa placeat fugiat reprehenderit, sit itaque saepe aut expedita, eos, accusantium minus! Aspernatur aperiam blanditiis impedit.
            Saepe itaque explicabo molestiae nemo soluta ex accusantium cum ducimus hic voluptatibus commodi architecto harum expedita dolore laboriosam quibusdam, animi quisquam corrupti possimus. Soluta similique totam omnis obcaecati fugiat et!
            Amet earum perspiciatis eligendi sapiente, modi deserunt saepe consequatur doloremque aspernatur adipisci eos deleniti consectetur atque aperiam reprehenderit officia, ex accusamus nemo labore fuga. Eveniet minus dolores porro atque sed?
            Eaque, facere. Autem blanditiis velit, aliquam praesentium sequi id cum obcaecati odit cumque commodi sed, laboriosam officiis illum modi fuga. Explicabo error, reprehenderit beatae veritatis suscipit similique quos ullam magni.
            Dignissimos iste esse explicabo soluta et ullam minima magnam porro labore debitis hic, dolorum, pariatur quis, facere cum aliquid. Debitis quo eum distinctio fugit corporis. Enim fuga reiciendis tempore esse?
            Pariatur, perferendis itaque eligendi temporibus ex excepturi fugit! Ea explicabo voluptatem iure ullam, voluptates illum laborum non voluptatum earum ipsa dicta deserunt odio aliquid nisi nulla nobis neque dolorum magni!
            Voluptatem consequuntur reiciendis omnis perspiciatis inventore distinctio beatae, officia voluptates enim quaerat magni adipisci iure cum dolorem odit aliquid exercitationem iste ipsam quam! Veniam eaque consequuntur cum quae quia harum!
            Ducimus iusto, aspernatur dicta rem reiciendis minima excepturi, impedit quos fugiat numquam debitis aperiam perspiciatis voluptate quibusdam sed molestiae! Molestias suscipit illum dolor autem deleniti sint incidunt! Quaerat, reprehenderit culpa?
            Temporibus quisquam suscipit vitae in obcaecati quod officia magnam itaque vero possimus accusamus ut explicabo, asperiores officiis esse sunt hic, dicta debitis! Ducimus rerum sit ea dolorum molestias unde praesentium.
            Minima ipsam quibusdam quaerat nobis vero aperiam autem excepturi vel. Culpa fugit mollitia totam corporis voluptatibus ipsa, sit quos, amet impedit provident ullam saepe dolorum numquam possimus veniam labore assumenda.
            Sed laborum ea, impedit magnam reprehenderit doloremque officiis distinctio ratione assumenda maiores nesciunt natus molestiae quidem, sunt quae! Minima suscipit illo architecto adipisci corrupti cum quam sapiente eum fugit quia.
            Ducimus aliquam assumenda laudantium repellendus blanditiis delectus quos quia sint eius. Accusamus provident vel non autem, quia fuga cupiditate consectetur earum alias, nam sint? Aperiam qui dicta consequuntur officiis accusantium.
            Hic laboriosam sed exercitationem nobis rem perspiciatis labore ut unde suscipit, tempora odit, veritatis distinctio omnis in aliquid? Debitis deleniti fuga voluptatibus consequuntur eius cupiditate ipsam inventore modi mollitia quasi.
            Sequi exercitationem hic aspernatur, suscipit porro quod magni. Illo, asperiores dolorem molestias, eos dolores suscipit maxime nam quia tenetur a recusandae, optio aperiam nemo ullam. Fugit sint eius asperiores eum.
            Cum quibusdam libero vero distinctio ea sint dolorum quo id praesentium. Exercitationem illum illo pariatur aliquid repellat rerum aut dolorem. Consequatur possimus praesentium assumenda porro asperiores. Deleniti accusamus repellendus dolorum?
            Nesciunt facere officiis quaerat culpa suscipit? Et a facere odit quas! Enim beatae itaque autem, quas error incidunt minima? Dolor sunt odio ducimus molestiae dolorum fuga ipsam, laborum soluta vitae?
            Minus vitae dolorem eos, dolores, enim laboriosam impedit velit minima est nesciunt assumenda sed explicabo illum tempore error! Velit, inventore? Iusto aliquam natus tenetur odio modi voluptatum ducimus dolores tempore!
            Debitis ducimus maxime fugiat soluta qui nisi sint non provident ab nobis optio necessitatibus, consectetur quisquam illo maiores blanditiis nostrum itaque asperiores quod ipsa eveniet id quos corporis beatae. Veniam.
            Rerum minus laudantium nam sed, eum hic officiis, porro ullam, iure voluptatum dolorum quam nesciunt assumenda quibusdam commodi consectetur doloremque veritatis earum. Earum minima quasi animi aperiam aut autem nesciunt!
        </p>
    )
}

export { Lorem };